"use client";

import { FileText, PieChart, AlertTriangle, BookOpen, Download, Calendar } from "lucide-react";
import Sidebar from "../components/Sidebar";

const reportCategories = [
  {
    title: "Daily Closing",
    icon: <FileText className="text-blue-600" size={18} />,
    bg: "bg-blue-50",
    links: ["Day Book (General)", "Cash Scroll (Counter)", "Transfer Scroll", "Denomination Tally"],
    button: "Generate Day End"
  },
  {
    title: "Financial Statements",
    icon: <PieChart className="text-green-600" size={18} />,
    bg: "bg-green-50",
    links: ["Trial Balance (Detailed)", "Profit & Loss A/c", "Balance Sheet", "GL Head Summary"],
    button: "View Financials"
  },
  {
    title: "Loan & Risk Reports",
    icon: <AlertTriangle className="text-amber-600" size={18} />,
    bg: "bg-amber-50",
    links: ["Loan Disbursement Register", "Interest Due List", "NPA / Overdue List (>90 Days)", "Demand Notice Generation"],
    button: "Check Risk",
    highlightIndex: 2
  },
  {
    title: "Statutory Registers",
    icon: <BookOpen className="text-purple-600" size={18} />,
    bg: "bg-purple-50",
    links: ["Member Admission Register", "Share Capital Register", "Nominee Register", "Director's Meeting Log"],
    button: "View Registers"
  }
];

const recentReports = [
  { name: "Day Book", date: "16 Dec 2025", user: "Manager (Sunil)", time: "05:15 PM", format: "PDF", formatBg: "bg-red-100 text-red-700" },
  { name: "NPA List (Overdue)", date: "Nov 2025", user: "Auditor", time: "11:30 AM", format: "XLS", formatBg: "bg-green-100 text-green-700" },
  { name: "Trial Balance", date: "FY 2024-25 (YTD)", user: "Manager (Sunil)", time: "Yesterday", format: "PDF", formatBg: "bg-red-100 text-red-700" },
];

export default function ReportsCenter() {
  return (
    <div className="flex h-screen bg-indigo-200 overflow-hidden">
      <Sidebar />
      
      <div className="flex-1 overflow-y-auto p-8">
        {/* Header */}
        <div className="flex justify-between items-start mb-8">
          <div>
            <h1 className="text-2xl font-bold text-slate-900 tracking-tight">Reports Center</h1>
            <p className="text-sm text-slate-500 mt-1 font-medium">Generate Day Book, Trial Balance, and Audit Statements</p>
          </div>
          <div className="bg-white border border-slate-200 px-4 py-2 rounded-lg flex items-center gap-2 shadow-sm">
            <Calendar size={16} className="text-slate-400" />
            <span className="text-xs font-black text-slate-900 uppercase">Today: 17 Dec 2025</span>
          </div>
        </div>

        {/* Report Category Grid */}
        <div className="grid grid-cols-4 gap-6 mb-10">
          {reportCategories.map((cat, i) => (
            <div key={i} className="bg-white rounded-xl border border-slate-200 shadow-sm flex flex-col">
              <div className="p-5 flex-1">
                <div className="flex items-center gap-3 mb-5">
                  <div className={`w-9 h-9 ${cat.bg} rounded-lg flex items-center justify-center`}>
                    {cat.icon}
                  </div>
                  <h3 className="text-sm font-black text-slate-800 uppercase tracking-tight">{cat.title}</h3>
                </div>
                <ul className="space-y-3">
                  {cat.links.map((link, idx) => (
                    <li key={idx} className={`text-[11px] font-bold tracking-tight ${cat.highlightIndex === idx ? 'text-red-600' : 'text-slate-500'}`}>
                      {link}
                    </li>
                  ))}
                </ul>
              </div>
              <div className="p-4 pt-0">
                <button className="w-full py-2 bg-[#F1F5F9] border border-slate-200 rounded-md text-[11px] font-black text-[#0047AB] uppercase hover:bg-slate-200 transition-colors">
                  {cat.button}
                </button>
              </div>
            </div>
          ))}
        </div>

        {/* Recently Generated Section */}
        <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
          <div className="px-6 py-4 border-b border-slate-100">
            <h3 className="text-sm font-black text-slate-800 uppercase tracking-tight">Recently Generated</h3>
          </div>
          <table className="w-full text-left">
            <thead>
              <tr className="bg-slate-50 border-b border-slate-200">
                <th className="px-6 py-3 text-[10px] font-black text-slate-400 uppercase tracking-widest">Report Name</th>
                <th className="px-6 py-3 text-[10px] font-black text-slate-400 uppercase tracking-widest">Period / Date</th>
                <th className="px-6 py-3 text-[10px] font-black text-slate-400 uppercase tracking-widest">Generated By</th>
                <th className="px-6 py-3 text-[10px] font-black text-slate-400 uppercase tracking-widest">Time</th>
                <th className="px-6 py-3 text-[10px] font-black text-slate-400 uppercase tracking-widest">Format</th>
                <th className="px-6 py-3 text-[10px] font-black text-slate-400 uppercase tracking-widest text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {recentReports.map((report, i) => (
                <tr key={i} className="hover:bg-slate-50/50 transition-colors">
                  <td className="px-6 py-4 text-xs font-black text-[#0047AB]">{report.name}</td>
                  <td className="px-6 py-4 text-xs font-bold text-slate-600">{report.date}</td>
                  <td className="px-6 py-4 text-xs font-bold text-slate-600">{report.user}</td>
                  <td className="px-6 py-4 text-xs font-bold text-slate-600">{report.time}</td>
                  <td className="px-6 py-4">
                    <span className={`px-2 py-0.5 rounded text-[9px] font-black ${report.formatBg}`}>
                      {report.format}
                    </span>
                  </td>
                  <td className="px-6 py-4 text-right">
                    <button className="text-[#0047AB] text-[11px] font-black uppercase hover:underline flex items-center gap-1 ml-auto">
                      Download
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}